/* translate jc-reverb in /xxxxxxxxxxxxxxxxxxxxxxxx/jcrev.ins to C
 *   written Fri 23-Jul-10 at 21:54 by CLM of 3-July-08
 */

#include <mus-config.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <math.h>
#include <signal.h>
#include <cmus.h>

static sig_atomic_t got_sigint = 0; /* catch C-C if hung */
static void sig_err(int sig) {got_sigint = sig;}

int clm_jc_reverb (double *clm_double, int datar_len, int *clm_int, int datai_len)
{
  /* The _clm_* variables are temporary values generated by the run macro */
  void (*old_SIGINT)(int);
  off_t I;
  bool CHAN4, CHAN2, DOUBLE, LOW_PASS;
  double _clm_71, _clm_70, _clm_69, _clm_67, _clm_66, _clm_65, _clm_58, _clm_57, _clm_55, _clm_50, _clm_43, _clm_42, _clm_40, _clm_35, _clm_30, _clm_27, _clm_26, _clm_25, _clm_24, _clm_19, _clm_18, _clm_17, _clm_16, _clm_15, _clm_11, _clm_10, _clm_9, HO, _clm_7, VOL, DELB, DELA, ALL_SUMS, COMB_SUM_2, COMB_SUM_1, COMB_SUM, ALLPASS_SUM;
  mus_any *OUTDEL4 = NULL, *OUTDEL2 = NULL, *_OUTPUT_ = NULL, *ENVA = NULL, *OUTDEL3 = NULL, *OUTDEL1 = NULL, *COMB4 = NULL, *COMB3 = NULL, *COMB2 = NULL, *COMB1 = NULL, *ALLPASS1 = NULL, *ALLPASS2 = NULL, *ALLPASS3 = NULL, *_REVERB_ = NULL;
  void *all_gens = NULL;
  off_t clm_beg, clm_end;
  
  all_gens = clm_make_genbag();
  clm_beg = clm_to_off_t(clm_int, 1);
  clm_end = clm_to_off_t(clm_int, 3);
  I = clm_int[35];
  ALLPASS_SUM = clm_double[15];
  COMB_SUM = clm_double[16];
  COMB_SUM_1 = clm_double[17];
  COMB_SUM_2 = clm_double[18];
  ALL_SUMS = clm_double[19];
  DELA = clm_double[20];
  DELB = clm_double[21];
  VOL = clm_double[22];
  LOW_PASS = (bool)clm_int[37];
  DOUBLE = (bool)clm_int[39];
  CHAN2 = (bool)clm_int[41];
  CHAN4 = (bool)clm_int[43];
  if ((CLM_FILE2SAMPLE_P(7)) || (CLM_FILE2FRAME_P(7)))
    _REVERB_ = clm_add_gen_to_genbag(all_gens, 
      mus_make_file_to_sample_with_buffer_size((char *)(clm_int + CLM_ILOC(7) + 2 + 2), clm_int[CLM_ILOC(7) + 1]));
  if (CLM_ALL_PASS_P(9))
    ALLPASS3 = clm_add_gen_to_genbag(all_gens, 
      mus_make_all_pass(
        clm_double[CLM_RLOC(9) + 1],/* feedback */
        clm_double[CLM_RLOC(9)],/* feedforward */
        clm_int[CLM_ILOC(9) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(9) + 2),/* delay line */
        clm_int[CLM_ILOC(9) + 3],/* max size */
        clm_int[CLM_ILOC(9) + 4]));/* interp type */
  if (CLM_ALL_PASS_P(11))
    ALLPASS2 = clm_add_gen_to_genbag(all_gens, 
      mus_make_all_pass(
        clm_double[CLM_RLOC(11) + 1],/* feedback */
        clm_double[CLM_RLOC(11)],/* feedforward */
        clm_int[CLM_ILOC(11) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(11) + 2),/* delay line */
        clm_int[CLM_ILOC(11) + 3],/* max size */
        clm_int[CLM_ILOC(11) + 4]));/* interp type */
  if (CLM_ALL_PASS_P(13))
    ALLPASS1 = clm_add_gen_to_genbag(all_gens, 
      mus_make_all_pass(
        clm_double[CLM_RLOC(13) + 1],/* feedback */
        clm_double[CLM_RLOC(13)],/* feedforward */
        clm_int[CLM_ILOC(13) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(13) + 2),/* delay line */
        clm_int[CLM_ILOC(13) + 3],/* max size */
        clm_int[CLM_ILOC(13) + 4]));/* interp type */
  if (CLM_COMB_P(15))
    COMB1 = clm_add_gen_to_genbag(all_gens, 
      mus_make_comb(
        clm_double[CLM_RLOC(15)],/* feedback */
        clm_int[CLM_ILOC(15) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(15) + 1),/* delay line */
        clm_int[CLM_ILOC(15) + 3],/* max size */
        clm_int[CLM_ILOC(15) + 4]));/* interp type */
  if (CLM_COMB_P(17))
    COMB2 = clm_add_gen_to_genbag(all_gens, 
      mus_make_comb(
        clm_double[CLM_RLOC(17)],/* feedback */
        clm_int[CLM_ILOC(17) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(17) + 1),/* delay line */
        clm_int[CLM_ILOC(17) + 3],/* max size */
        clm_int[CLM_ILOC(17) + 4]));/* interp type */
  if (CLM_COMB_P(19))
    COMB3 = clm_add_gen_to_genbag(all_gens, 
      mus_make_comb(
        clm_double[CLM_RLOC(19)],/* feedback */
        clm_int[CLM_ILOC(19) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(19) + 1),/* delay line */
        clm_int[CLM_ILOC(19) + 3],/* max size */
        clm_int[CLM_ILOC(19) + 4]));/* interp type */
  if (CLM_COMB_P(21))
    COMB4 = clm_add_gen_to_genbag(all_gens, 
      mus_make_comb(
        clm_double[CLM_RLOC(21)],/* feedback */
        clm_int[CLM_ILOC(21) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(21) + 1),/* delay line */
        clm_int[CLM_ILOC(21) + 3],/* max size */
        clm_int[CLM_ILOC(21) + 4]));/* interp type */
  if (CLM_DELAY_P(23))
    OUTDEL1 = clm_add_gen_to_genbag(all_gens, 
      mus_make_delay(
        clm_int[CLM_ILOC(23) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(23)),/* delay line */
        clm_int[CLM_ILOC(23) + 3],/* max size */
        clm_int[CLM_ILOC(23) + 4]));/* interp type */
  if (CLM_DELAY_P(25))
    OUTDEL3 = clm_add_gen_to_genbag(all_gens, 
      mus_make_delay(
        clm_int[CLM_ILOC(25) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(25)),/* delay line */
        clm_int[CLM_ILOC(25) + 3],/* max size */
        clm_int[CLM_ILOC(25) + 4]));/* interp type */
  if (CLM_ENV_P(27))
    ENVA = clm_add_gen_to_genbag(all_gens, 
      mus_make_env(
        (double *)(clm_double + CLM_RLOC(27) + 3), /* breakpoints */
        clm_int[CLM_ILOC(27) + 2], /* num points */
        clm_double[CLM_RLOC(27) + 1], /* scaler */
        clm_double[CLM_RLOC(27) + 2], /* offset */
        clm_double[CLM_RLOC(27)], /* base */
        0.0, /* dur useless here */
        clm_int[CLM_ILOC(27) + 3], /* end */
        NULL)); /* original data -- handled internally */
  _OUTPUT_ = clm_output();
  if (CLM_DELAY_P(31))
    OUTDEL2 = clm_add_gen_to_genbag(all_gens, 
      mus_make_delay(
        clm_int[CLM_ILOC(31) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(31)),/* delay line */
        clm_int[CLM_ILOC(31) + 3],/* max size */
        clm_int[CLM_ILOC(31) + 4]));/* interp type */
  if (CLM_DELAY_P(33))
    OUTDEL4 = clm_add_gen_to_genbag(all_gens, 
      mus_make_delay(
        clm_int[CLM_ILOC(33) + 2],/* size */
        (double *)(clm_double + CLM_RLOC(33)),/* delay line */
        clm_int[CLM_ILOC(33) + 3],/* max size */
        clm_int[CLM_ILOC(33) + 4]));/* interp type */
  if (clm_beg > clm_end) return(1);
  got_sigint = 0; old_SIGINT = clm_signal(SIGINT, sig_err);                     /* trap SIGINT */
  I = clm_beg;                                                                  /* pass counter */

SAMPLE_LOOP_BEGIN:
  if (got_sigint != 0) {clm_int[0] = (int)got_sigint; goto RUN_ALL_DONE;}
  if (I > clm_end) {I = clm_end; goto RUN_ALL_DONE;}
                                                                                /* (progn */
  _clm_7 = mus_in_any(I, 0, _REVERB_);
  HO = _clm_7;                                                                  /* (setf HO _clm_7) */
  _clm_11 = mus_all_pass_unmodulated(ALLPASS1, HO);
  _clm_10 = mus_all_pass_unmodulated(ALLPASS2, _clm_11);
  _clm_9 = mus_all_pass_unmodulated(ALLPASS3, _clm_10);
  ALLPASS_SUM = _clm_9;                                                         /* (setf ALLPASS-SUM _clm_9) */
  COMB_SUM_2 = COMB_SUM_1;                                                      /* (setf COMB-SUM-2 COMB-SUM-1) */
  COMB_SUM_1 = COMB_SUM;                                                        /* (setf COMB-SUM-1 COMB-SUM) */
  _clm_16 = mus_comb_unmodulated(COMB1, ALLPASS_SUM);
  _clm_17 = mus_comb_unmodulated(COMB2, ALLPASS_SUM);
  _clm_18 = mus_comb_unmodulated(COMB3, ALLPASS_SUM);
  _clm_19 = mus_comb_unmodulated(COMB4, ALLPASS_SUM);
                                                                                /* (+ _clm_16 _clm_17 _clm_18 _clm_19) */
  _clm_15 = ((_clm_16) + (_clm_17) + (_clm_18) + (_clm_19));
  COMB_SUM = _clm_15;                                                           /* (setf COMB-SUM _clm_15) */
                                                                                /* (if low-pass */
  if ((!LOW_PASS)) goto L_21;
                                                                                /* (+ comb-sum comb-sum-2) */
  _clm_26 = ((COMB_SUM) + (COMB_SUM_2));
                                                                                /* (* 0.25 _clm_26) */
  _clm_25 = ((0.25) * (_clm_26));
                                                                                /* (* 0.5 comb-sum-1) */
  _clm_27 = ((0.5) * (COMB_SUM_1));
                                                                                /* (+ _clm_25 _clm_27) */
  _clm_24 = ((_clm_25) + (_clm_27));
  ALL_SUMS = _clm_24;                                                           /* (setf ALL-SUMS _clm_24) */
  goto L_22;
L_21:
  ALL_SUMS = COMB_SUM;                                                          /* (setf ALL-SUMS COMB-SUM) */
L_22:
  _clm_30 = mus_delay_unmodulated(OUTDEL1, ALL_SUMS);
  DELA = _clm_30;                                                               /* (setf DELA _clm_30) */
                                                                                /* (if double */
  if ((!DOUBLE)) goto L_32;
  _clm_35 = mus_delay_unmodulated(OUTDEL3, ALL_SUMS);
  DELA += _clm_35;                                                              /* (incf DELA _clm_35) */
  goto L_33;
L_32:
L_33:
                                                                                /* (if enva */
  if ((!ENVA)) goto L_37;
  _clm_40 = mus_env(ENVA);                                                      /* (env ENVA) */
  VOL = _clm_40;                                                                /* (setf VOL _clm_40) */
  goto L_38;
L_37:
L_38:
                                                                                /* (* vol dela) */
  _clm_43 = ((VOL) * (DELA));
  _clm_42 = mus_out_any(I, _clm_43, 0, _OUTPUT_);
                                                                                /* (if chan2 */
  if ((!CHAN2)) goto L_46;
                                                                                /* (progn */
  _clm_50 = mus_delay_unmodulated(OUTDEL2, ALL_SUMS);
  DELB = _clm_50;                                                               /* (setf DELB _clm_50) */
                                                                                /* (if double */
  if ((!DOUBLE)) goto L_52;
  _clm_55 = mus_delay_unmodulated(OUTDEL4, ALL_SUMS);
  DELB += _clm_55;                                                              /* (incf DELB _clm_55) */
  goto L_53;
L_52:
L_53:
                                                                                /* (* vol delb) */
  _clm_58 = ((VOL) * (DELB));
  _clm_57 = mus_out_any(I, _clm_58, 1, _OUTPUT_);
                                                                                /* (if chan4 */
  if ((!CHAN4)) goto L_61;
                                                                                /* (progn */
  _clm_67 = mus_delay_unmodulated(OUTDEL3, ALL_SUMS);
                                                                                /* (* vol _clm_67) */
  _clm_66 = ((VOL) * (_clm_67));
  _clm_65 = mus_out_any(I, _clm_66, 2, _OUTPUT_);
  _clm_71 = mus_delay_unmodulated(OUTDEL4, ALL_SUMS);
                                                                                /* (* vol _clm_71) */
  _clm_70 = ((VOL) * (_clm_71));
  _clm_69 = mus_out_any(I, _clm_70, 3, _OUTPUT_);
  goto L_62;
L_61:
L_62:
  goto L_47;
L_46:
L_47:
  I++;                                                                          /* increment pass counter and loop */
goto SAMPLE_LOOP_BEGIN;

RUN_ALL_DONE:
  clm_signal(SIGINT,old_SIGINT);
  if (all_gens) clm_free_genbag(all_gens);

  return(1);
}

